# Uncomment this line to define a global platform for your project
#platform :ios, '8.0'

#use_frameworks!

target 'Dreamscape' do
    pod "CSStickyHeaderFlowLayout"
    pod 'Firebase', '>= 2.4.2'
    pod 'DZNEmptyDataSet'
end

