# Uncomment this line to define a global platform for your project
#platform :ios, '8.0'

#use_frameworks!

target 'Dreamscape' do
    pod "CSStickyHeaderFlowLayout"
    pod 'DZNEmptyDataSet'
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
    pod 'Firebase/Database'
    pod 'Fabric'
    pod 'TwitterKit'
end

